baseURL = "http://example.org/"
languageCode = "zh-CN"
title = "Wish You All the Best✔️"
theme = "webstack-hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = "shark"
[params]
  author = "iplaycode"
  description = "Webstack Hugo"
